- hosts: Production

  vars_files:
    - "../vars.yml"

  tasks:

    - name: Generate random password
      shell: tr -dc A-Za-z0-9_ < /dev/urandom | head -c 16 | xargs 2>/dev/null
      register: password

    - name: Create new Prodaction vhost
      rabbitmq_vhost:
        name: '{{prod_vhost}}'

    - name: Create new user
      rabbitmq_user:
        user: '{{ new_user }}'
        password: '{{ password.stdout }}'
        tags: monitoring
        permissions:
        - vhost: '{{prod_vhost}}'
          configure_priv: .*
          read_priv: .*
          write_priv: .*

    - name: Policies for Prodaction vhost
      rabbitmq_policy:
        vhost: '{{prod_vhost}}'
        name: HA
        pattern: .*
        priority: 0
        tags:
          ha-mode: all
          ha-sync-mode:	automatic

    - debug:
        msg:
          - '############## PRODUCTION #################'
          - 'URL Monitor: https://clusterrmq.sberned.ru '
          - 'HOST: rmqcluster.rmq '
          - 'PORT: 5672 '
          - 'USER: {{ new_user }} '
          - 'PASSWORD: {{ password.stdout }} '
          - 'VHOST: {{ prod_vhost }}'
          - '###########################################'
